### ISSUE TITLE
SymbolsNotMatchingException - Mono.Cecil crashes when mismatching symbols are found

### ISSUE THREAD

**Issue by MikeStacey-Gee** [codingadventures/LINQBridgeVs#48]
I keep seeing this in the log file:

2018-07-10T14:50:58.5818167+01:00 Assembly being Injected C:\Development\CMSi\CMSi-Full\ams\AMS-MDI\bin\Debug\CMSI-MDI.exe
2018-07-10T14:50:59.0958376+01:00 Error Executing MSBuild Task SInjectionBuildTask - 
SymbolsNotMatchingException: Symbols were found but are not matching the assembly
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader, Boolean throwIfSymbolsAreNotMaching)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at BridgeVs.Build.SInjection..ctor(String assemblyLocation, String snkCertificatePath, PatchMode mode)
   at BridgeVs.Build.Tasks.SInjectionBuildTask.Execute()

No visualizers are output

**Comment by codingadventures** [comment]
Hi Mike,

I've seen that error coming through a lot in Sentry, it happened to me as well during development and testing, I am still not sure what it's firing it. Does it happen only with a specific assembly? Could you try to clear manually the content of the debug folder and do a rebuild?

That error also blocks the compilation process, so if that error occurs it stops from creating the assembly, I should change that

**Comment by MikeStacey-Gee** [comment]
Will do, and get back to you.

**Comment by codingadventures** [comment]
fixed in the next release
