### ISSUE TITLE
Windows x86 - Error during installation - v1.4.6

### ISSUE THREAD

**Issue by Elixir4575** [codingadventures/LINQBridgeVs#49]
The type initializer for 'BridgeVs.Shared.Common.CommonFolderPaths' threw an exception. 
    at BridgeVs.VsPackage.Helper.Configuration.PackageConfigurator.IsLINQPadInstalled(String vsVersion)
   at BridgeVs.VsPackage.Helper.Configuration.PackageConfigurator.Install(String vsVersion, String vsEdition)
   at BridgeVs.VsPackage.Package.BridgeVsPackage.Initialize()
 Value cannot be null.
Parameter name: path1    at System.IO.Path.Combine(String path1, String path2)
   at BridgeVs.Shared.Common.CommonFolderPaths..cctor()

**Comment by codingadventures** [comment]
Hi, has this occured on a 32bit version of Windows? could you please share the OS info

**Comment by codingadventures** [comment]
I believe this was caused because there is no **_C:\Program Files (x86)_** folder which exists only on x64 version of Windows.

**Comment by codingadventures** [comment]
fixed in the next release
